<div class="custTableHeading">
    <div class="radioWrap">&nbsp;</div>
    <div class="custNo"><?php echo $this->__('CustNo')?><span class="sortButton"></span></div>
    <div class="custName"><?php echo $this->__('Name') ?></div>
    <div class="country"><?php echo $this->__('Country') ?></div>
    <div class="state"><?php echo $this->__('City') ?></div>
    <div class="email"><?php echo $this->__('Email') ?></div>
    <div class="seller"><?php echo $this->__('Seller') ?><span class="sortButton"></span></div>
    <div class="agent"><?php echo $this->__('Agent') ?><span class="sortButton"></span></div>
    <div class="editItem">&nbsp;</div>
</div>
<?php
    $user = $this->getResellerFilterCollection();
    $count = count($user);
    foreach ($user as $key => $value) :
        $address_id = $value->getDefaultBilling();
        $address = Mage::getModel('customer/address')->load($address_id);
?>
        <div class="custDataRow">
            <div class="radioWrap">
                <div class="radioBtnWrap"><input class="radioBtn" type="radio" name="cust" value="<?php echo $value['entity_id'] ?>" onclick="selectCustomerRadio(this)" /></div>
            </div>
            <div class="custNo">
                <span><?php echo (!empty($value['prefix']) ? $value['prefix'] : '&nbsp'); ?></span>
            </div>
            <div class="custName">
                <span><?php echo (!empty($value['firstname']) ? $value['firstname'] : '&nbsp'); ?></span>
            </div>
            <div class="country">
                <span><?php
                $country = $address->getCountry();
                echo (!empty($country) ? $country : '&nbsp');
                ?></span>
            </div>
            <div class="state">
                <span><?php
                $city = $address->getCity();
                echo (!empty($city) ? $city : '&nbsp');
                ?></span>
            </div>
            <div class="email">
                <span><?php echo (!empty($value['email']) ? $value['email'] : '&nbsp'); ?></span>
            </div>
            <div class="seller">
            <?php
            $attributeCode = 'seller';
            $attributeDetailsSecond = Mage::getSingleton("eav/config")->getAttribute("customer", $attributeCode);
            $optionsAll = $attributeDetailsSecond->getSource()->getAllOptions(false);
            $valueSeller = '';
            foreach ($optionsAll as $option) {
                if ($option["value"] == $value['seller']) {
                    $valueSeller = $option["label"];
                }
            }
            ?>
                <span><?php echo (!empty($valueSeller) ? $valueSeller : '&nbsp'); ?></span>
            </div>
            <div class="agent">
            <?php
                $attributeCodeAgent = 'agent';
                $attributeDetailsAgent = Mage::getSingleton("eav/config")->getAttribute("customer", $attributeCodeAgent);
                $optionsAllAgent = $attributeDetailsAgent->getSource()->getAllOptions(false);
                $valueAgent = '';
                foreach ($optionsAllAgent as $optionsAllAgentEach) {
                    if ($optionsAllAgentEach["value"] == $value['agent']) {
                        $valueAgent = $optionsAllAgentEach["label"];
                    }
                }
            ?>
                <span><?php echo (!empty($valueAgent) ? $valueAgent : '&nbsp'); ?></span>
            </div>
            <div class="editItem">
                <button class="editItemButton" onclick="window.location = '<?php echo Mage::getUrl('reseller/index/customerdetailspage') . "?value=" . $value['entity_id']; ?>'"><span class="glyphicon glyphicon-pencil"></span></button>
            </div>
        </div>
        <?php
    endforeach;
?>